### PR TITLE
Add localhost install

### PR DESCRIPTION
**Pull request by evilnick**
image

### CODE REVIEW

**Comment by evilnick** [comment]
@ktsakalozos There is a 'manual install' page in progress. I wasn't specifically going to mention localhost there. but I could do and add a link here when it is done.

Good point about LXD. Making instructions that will work with different versions of LXD, installed in different ways (deb/snap) and potentially for different platforms gets complex pretty quicklyand starts to resemble some sort of choose-your-own-adventure book. I will add a warning though!

**Comment by evilnick** [comment]
@ktsakalozos I think those changes ^  should be okay for the pre-installed LXD issue

**Comment by ktsakalozos** [comment]
Final, comment :) .  I see you used the word "recommend". The use of `dir` in `lxd init` and the snapped `lxd` are strong recommendations more towards "you are playing with fire if you do not follow these recommendations". Can we do anything about those points?

**Comment by evilnick** [comment]
reworded now

**Comment by ktsakalozos** [comment]
LGTM +1

**Pull request merged**
